### ISSUE TITLE
Extrinsic Parameters coordinate frames

### ISSUE THREAD

**Issue by rakshith95** [rpng/open_vins#154]
Hello, 
In the documentation for the measurement update (https://docs.openvins.com/update-feat.html#relative), 
![image](https://user-images.githubusercontent.com/33649411/112225321-df6f6000-8c2c-11eb-9629-8c8da6407a5d.png)

Why is the extrinsic parameters (Rotation, translation) defined this way? Afaik the standard is to define them as transforms from a World frame ---> Camera frame, which would mean that Rotation and translation are defined as the pose of the global frame in the camera coordinate frame.

**Comment by goldbattle** [comment]
When you say "extrinsics" you are referring to the current frame estimate and not the sensor extrinsics I assume.
This is due to the convention of the original MSCKF paper's state definition and all works which derive from the original paper.
It doesn't make much a difference as long as you are consistent in how you take your derivatives and update those state elements.

**Comment by rakshith95** [comment]
@goldbattle 
I was referring to the line in the picture above which says "{R,p} denote the current camera pose and orientation in the global frame (or camera extrinsics)" 
I thought this meant that the sensor extrinsics were defined as such.

**Comment by goldbattle** [comment]
The pose is a function of the camera extrinsics (underlined in red):
![image](https://user-images.githubusercontent.com/2222562/112676662-14eb9780-8e3f-11eb-9365-ec6791e44824.png)

**Comment by rakshith95** [comment]
Alright, thank you. Closing this
