### ISSUE TITLE
Is set the first measurement to be the anchor frame?

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [rpng/open_vins#183]
In function "FeatureInitializer::single_triangulation", you set the last frame to be the anchor frame, why don't you set the first frame here to be the anchor frame?

**Comment by goldbattle** [comment]
It can be arbitrary. We chose it to save a small amount of compute since if you anchor it in the older frame (and use an anchored feature representation) the feature will need its anchored to be moved since the oldest pose is always marginalized (see the [anchor feature change function](https://docs.openvins.com/classov__msckf_1_1UpdaterSLAM.html#ae85d162f1a93f1dbed1a60b2fdd26870)).
