### ISSUE TITLE
trajectory problem

### ISSUE THREAD

**Issue by chenyong1003** [rpng/open_vins#188]
sorry to bother you again! I can't use EVO to evaluate my data after it is saved.Is there any way to solve this?
![932D676E-7EAE-45DC-ABED-B56EECE31CCC](https://user-images.githubusercontent.com/87304070/126926792-bc7daa57-2fee-4f84-9878-3c6a88ff99de.png)

**Comment by goldbattle** [comment]
We recommend you use the built in ov_eval utility instead if you need an out of the box solution.
https://docs.openvins.com/namespaceov__eval.html

Otherwise you will need to convert to their format if needed, note that we record with a space separated file.
Referred to as the RPE format instead of the Euroc file format and vice-versa.
See the documentation site:
https://docs.openvins.com/eval-error.html#eval-ov-transform

I am not sure if the [EVO](https://github.com/MichaelGrupp/evo) package supports space separated, but you could try looking at their documentation or opening an issue on their github. Hope this helps.

**Comment by chenyong1003** [comment]
I used the method you said,it appeared the following problem.
![33937598-D1C3-4B2A-8CBE-67AE2ECCE1E3](https://user-images.githubusercontent.com/87304070/127149455-4aa39cf7-3781-42bf-983b-d5c121e2c85a.png)

**Comment by goldbattle** [comment]
You need to source your ros workspace once you build the open_vins ov_eval package.
