### ISSUE TITLE
Memory Usage increase rapidly 

### ISSUE THREAD

**Issue by Majed-Alsubaie** [rpng/open_vins#190]
Hi,,
Thank you for releasing such a project ,, it is wonderful 

I face an issue with the memory where i do small movement  and stop then " [ZUPT]: chi2_check over the residual limit - 1878" appears on the terminal
After a while memory usage start jump!

see the video:https://drive.google.com/file/d/1xwCiOIDcFVQd1x-HqOusPo-TWpSr_R8z/view?usp=sharing

i have tested the same launch file with Mh-01 ,,, the algorithm did great! 
the launch file : https://drive.google.com/file/d/11EJbk5BCRNWUasFv4mxewFNC9Bn5nGgm/view?usp=sharing

**Comment by goldbattle** [comment]
This might be due to how we keep a history of visual tracks and IMU readings.
Are you using the latest commit from the main branch?

**Comment by goldbattle** [comment]
This also seems to be reported in this paper, needs to be investigated.
https://arxiv.org/pdf/2108.01654.pdf
![image](https://user-images.githubusercontent.com/2222562/130467369-6d6a7589-9002-4dff-85a1-cff04faf6237.png)

Probably due to how we store IMU data and need to have better logic to handle that deletion or how we store historical image track information in our feature database (maybe measurement delete logic doesn't work?).

**Comment by goldbattle** [comment]
Unable to reproduce currently on my machine (Ubuntu 20.04).
