### ISSUE TITLE
Why is the error status updated without subtracting H*delta{x}?

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [rpng/open_vins#195]
Openvins uses the error-state Kalman Filter method，I find that in the error status update , you don't subtract H*deltax.(StateHelper::EKFUpdate)
`Eigen::VectorXd dx = K * res;`
I think it should be K(res-H *delta_x), why is there no part about delta_x in the code?

**Comment by goldbattle** [comment]
Hi, we use an Extended Kalman Filter since these are non-linear measurements.
The docs provide an example for how to do it with a linear measurement.
https://docs.openvins.com/update.html

I recommend you read up on EKFs or just take a look a wikipedia:
https://en.wikipedia.org/wiki/Extended_Kalman_filter

**Comment by goldbattle** [comment]
Answered via issue #200.
