### ISSUE TITLE
Roll and yaw have a constant offset compared to GroundTruth when running with EuRoC. 

### ISSUE THREAD

**Issue by hungdche** [rpng/open_vins#303]
Hi, 

I'm trying to run OpenVINS with EuRoC, and it seems that although the xyz and pitch match well, both roll and yaw differ have a constant offset of about 50 degree compared to ground truth.   
![image](https://user-images.githubusercontent.com/90811347/213965631-4cd9fce2-30a2-4211-93fb-f336310d1572.png)
![image](https://user-images.githubusercontent.com/90811347/213960155-2327bee1-b005-4402-8547-82db3455d252.png)

The config file that I used is the [exact ones](https://github.com/rpng/open_vins/tree/master/config/euroc_mav) provided by OpenVINS. My code is [here](https://github.com/hungdche/open_vins/blob/master/ov_msckf/src/run_illixr_msckf.cpp) just in case. 

Any help for pointer is greatly appreciated. Thanks!

**Comment by goldbattle** [comment]
This might be due to your use of the quaternion.
We use a JPL quaternion which is the rotation from the GLOBAL to the IMU
frame.
I recommend you try writing the quaternion x,y,z,w to file, and then
processing it.
When a JPL quaternion is written in this order, and read as a Halmiton
quaternion, it flips the rotation direction to IMU to GLOBAL.

**Comment by hungdche** [comment]
Thank you for your response! It does in fact match now
