### ISSUE TITLE
NaN problem in dynamic initialization

### ISSUE THREAD

**Issue by CanCanZeng** [rpng/open_vins#312]
Hi, I got NaN velocity for sigmas_vel  and sigmas_bg and sigmas_ba sometimes in dynamic initialization, thus cause the system crash later. Maybe the calibration between camera and imu is not very accurate, can you give me some advice on solving this problem?

**Comment by CanCanZeng** [comment]
Yes, you are right! I find that the NaN most probabaly caused by degenerate of motion. So I both increase the min reciprocal number and check the distance between the first frame and the last frame, if the distance is too small, the motion may degenerated. This strategy has worked so far, don't know if there will be other cases in the future.

**Comment by goldbattle** [comment]
You can try to change the `init_imu_thresh` and `init_max_disparity` as when the platform is stationary static initialization can be used directly and skip dynamic initialization. If you have stereo, then you should be able to always initialize right away with the dynamic init (don't know if I have tested this, but since features can be triangulated, it should work).
