### ISSUE TITLE
failed static init: no accel jerk detected, platform moving too much

### ISSUE THREAD

**Issue by meepo20** [rpng/open_vins#347]
ros2 launch ov_msckf subscribe.launch.py config:=euroc_mav max_cameras:=1
ros2 bag play <file>

Getting this error when I play from a ROS2 bag.
How to save map as well as other relevant data to use with OV_EVAL
Are there any guides on how to use OV_EVAL I'd like to use it to check the RPE

**Comment by goldbattle** [comment]
The most recent points are published on `/ov_msckf/loop_feats` so this can be helpful if you want to reconstruct an incremental map. The code only keeps track of a local map since this is an odometry method, thus no code currently saves the map, nor evaluates it.

To evaluate error, please checkout the documentation website:
- https://docs.openvins.com/eval-metrics.html#eval-rpe
- https://docs.openvins.com/eval-error.html#eval-ov-plot-singlerun
