### ISSUE TITLE
document about StateHelper class ?

### ISSUE THREAD

**Issue by chennuo0125-HIT** [rpng/open_vins#371]
thanks for this greate work, but I cant understand the implementation about class StateHelper, could provide document ?

**Comment by goldbattle** [comment]
Hi. The documentation is provided here:
- https://docs.openvins.com/classov__msckf_1_1StateHelper.html
- https://docs.openvins.com/dev-index.html

If you wish the understand the underling implementation I recommend reading the code directly as there are sufficient comments. Otherwise just looking at the function documentation is likely sufficient.
