### ISSUE TITLE
system is divergent after the hardware(vio-sensors) stay static for a while?   

### ISSUE THREAD

**Issue by Wangxuefeng92** [rpng/open_vins#77]
hi, I got some problem with open-vins.
I carried my vio-sensor, and  walked around  for a long-term, then I stayed  static for a while. then I found that the trajectory is divergent, also the residual is divergent... 
hoping for your reply!

**Comment by goldbattle** [comment]
This can happen if you lose track of your SLAM features and there isn't a zero velocity update. We will hopefully open source the zero velocity update soon (not sure on the timeline). But you can avoid this by making sure you track a lot of SLAM features and they are able to be continuously tracked when you are still.

The underlying computer vision issue is that you cannot triangulate any *new* features if you are still since there is no parallax between features.

**Comment by Wangxuefeng92** [comment]
thanks for your reply！I am also wandering that how to detect the “STATIC” condition for a vio system. Because the vision or imu measurement is so noisy, and the vio system can also slight jitter sometimes.

**Comment by rpng-guest** [comment]
PR #79 should address this, feel free to try it out (does require some tuning of the detection thresholds).
